ervices:
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - /home/josh/ollama/data:/root/.ollama
    container_name: ollama
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  stable-diffusion-webui:
    image: universonic/stable-diffusion-webui:minimal
    command: --no-half --no-half-vae --precision full
    runtime: nvidia
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
    volumes:
      - /home/josh/stable-diffusion/data/inputs:/app/stable-diffusion-webui/inputs
      - /home/josh/stable-diffusion/data/textual_inversion_templates:/app/stable-diffusion-webui/textual_inversion_templates
      - /home/josh/stable-diffusion/data/embeddings:/app/stable-diffusion-webui/embeddings
      - /home/josh/stable-diffusion/data/extensions:/app/stable-diffusion-webui/extensions
      - /home/josh/stable-diffusion/data/models:/app/stable-diffusion-webui/models
      - /home/josh/stable-diffusion/data/localizations:/app/stable-diffusion-webui/localizations
      - /home/josh/stable-diffusion/data/outputs:/app/stable-diffusion-webui/outputs
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.iface != extern"
      restart_policy:
        condition: unless-stopped
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - /home/josh/open-webui/data:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
